#!/bin/sh
# Since 2010
xsltproc paperlist.xml > output/paperlist_sinceFY2010.html
cp output/paperlist_sinceFY2010.html paperlist_sinceFY2010.html
xsltproc toBibTeX.xsl paperlist.xml > output/paperlist_sinceFY2010.bib

# All
xmllint --xinclude paperlist_all.xml > output/__paperlist_included.xml
xsltproc -o output/paperlist.html paperlist.xsl output/__paperlist_included.xml
# cp output/paperlist.html ../index.html
xsltproc -o output/paperlist4A.html paperlist4A.xsl output/__paperlist_included.xml
xsltproc toLaTeX.xsl output/__paperlist_included.xml | sed -f toLaTeX.sed > output/paperlist.tex
platex -kanji=utf8 output/paperlist.tex
dvipdfmx paperlist.dvi

xsltproc toBibTeX.xsl output/__paperlist_included.xml > output/paperlist.bib
xsltproc toCSV_B.xsl output/__paperlist_included.xml | html2text -width 100000 -nobs | sed "s/, /,/g" | sed "s/_/ /g" > output/B.csv
xsltproc toCSV_C.xsl output/__paperlist_included.xml | html2text -width 100000 -nobs | sed "s/, /,/g" | sed "s/_/ /g" > output/C.csv